hko7: &hko7
  type: hko7_mp
  input_length: 10
  pred_length: 10
  base_freq: 6min

dataset:
  train:
    <<: *hko7

  valid:
    <<: *hko7

sampler:
  type: TrainingSampler

dataloader:
  num_workers: 8 
  pin_memory: False
  prefetch_factor: 2
  persistent_workers: True

trainer:
  batch_size: 16 # to check
  test_batch_size: 16
  max_epoch: &max_epoch 1
  max_step: 30000

model:
  type: dec_model
  params:
    sub_model:
      PredRNN:
        num_layers: 4
        num_hidden: [128, 128, 128, 128]
        img_channel: 1
        img_width: 480 
        img_height: 480
        patch_size: 10
        stride: 1 
        filter_size: 3

    save_best: &loss_type MSE
    use_ceph: True
    metrics_type: hko7
    ceph_checkpoint_path: "mpas:s3://hko7/checkpoint"
    data_type: fp32

    optimizer:
      PredRNN:
        type: AdamW
        params:
          lr: 0.001
          betas: [0.9, 0.95]
          # eps: 0.000001

    lr_scheduler:
      PredRNN:
        by_step: True
        sched: cosine
        epochs: *max_epoch
        min_lr: 0.
        warmup_lr: 0.
        warmup_epochs: 0.0033
        lr_noise: 
        cooldown_epochs: 0

    extra_params:
      loss_type: MSELoss
      enabled_amp: False
      log_step: 20
      z_score_delta: False


