sevir: &sevir
  type: sevir_latent25
  input_length: &input_length 13 
  pred_length: &pred_length 12
  total_length: &total_length 25
  base_freq: 5min
  data_dir: radar:s3://sevir_latent
  latent_size: 48x48x4

dataset:
  train:
    <<: *sevir

  valid:
    <<: *sevir

sampler:
  type: TrainingSampler

dataloader:
  num_workers: 8
  pin_memory: False
  prefetch_factor: 2
  persistent_workers: True

trainer:
  batch_size: 16 # to check
  valid_batch_size: 3
  max_epoch: &max_epoch 1
  max_step: 100000

model:
  type: latent_nonar_pred_model
  params:
    sub_model:
      vit:
        arch: vit_custom
        patch_size: [1, 1]
        in_chans: 52
        out_chans: 48
        learnable_pos: True
        window: True,
        drop_path_rate: 0.
        round_padding: True
        pad_attn_mask: True 
        test_pos_mode: 'learnable_simple_interpolate' # to_do: ablation
        lms_checkpoint_train: False
        img_size: [48, 48]
        arch_dict:
          use_abs_pos_emb: True
          embed_dim: 256
          depth: 12
          num_heads: 8
          mlp_ratio: 4
          qkv_bias: True
      
      autoencoder_kl:
        in_channels: 1
        out_channels: 1
        down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D']
        up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
        block_out_channels: [128, 256, 512, 512]
        layers_per_block: 2
        latent_channels: 4
        norm_num_groups: 32

    save_best: &loss_type MSE
    use_ceph: True
    ceph_checkpoint_path: "mpas:s3://sevir/checkpoint"
    metrics_type: SEVIRSkillScore
    data_type: fp32

    visualizer:
      visualizer_type: sevir_visualizer
      visualizer_step: 500

    optimizer:
      vit:
        type: AdamW
        params:
          lr: 0.001
          betas: [0.9, 0.999]
          weight_decay: 0.00001
          # eps: 0.000001

    lr_scheduler:
      vit:
        by_step: True
        sched: cosine
        epochs: *max_epoch
        min_lr: 0.
        warmup_lr: 0.
        warmup_epochs: 0.2
        lr_noise: 
        cooldown_epochs: 0

    extra_params:
      loss_type: MSELoss
      enabled_amp: False
      log_step: 20
      metric_epoch_interval: 10
      z_score_delta: False
      autoencoder_checkpoint_path: autoencoder_kl_gan/world_size4-48x48x4_40W/checkpoint_latest.pth