sevir: &sevir
  type: sevir
  input_length: &input_length 13 
  pred_length: &pred_length 12
  total_length: &total_length 25
  base_freq: 5min
  data_dir: radar:s3://weather_radar_datasets/sevir

dataset:
  train:
    <<: *sevir

  valid:
    <<: *sevir

sampler:
  type: TrainingSampler

dataloader:
  num_workers: 8 
  pin_memory: False
  prefetch_factor: 2
  persistent_workers: True

trainer:
  batch_size: 8 # to check
  valid_batch_size: 12
  max_epoch: &max_epoch 1
  max_step: 100000

model:
  type: videogpt_vqvae_model
  params:
    sub_model:
      videogpt_vqvae:
        embedding_dim: 256
        n_hiddens: 240
        n_res_layers: 4
        downsample: [4, 4, 4]
        n_codes: 2048
        sequence_length: 12
        resolution: 384

    save_best: &loss_type MSE
    use_ceph: True
    ceph_checkpoint_path: "mpas:s3://sevir/checkpoint"
    metrics_type: SEVIRSkillScore
    data_type: fp32

    visualizer:
      visualizer_type: sevir_visualizer
      visualizer_step: 500

    optimizer:
      videogpt_vqvae:
        type: AdamW
        params:
          lr: 0.0005
          betas: [0.9, 0.999]
          weight_decay: 0.00001
          # eps: 0.000001

    lr_scheduler:
      videogpt_vqvae:
        by_step: True
        sched: cosine
        epochs: *max_epoch
        min_lr: 0.00005
        warmup_lr: 0.00005
        warmup_epochs: 0.1
        lr_noise: 
        cooldown_epochs: 0
      

    extra_params:
      loss_type: MSELoss
      enabled_amp: False
      log_step: 20
      z_score_delta: False
      # checkpoint_path: EarthFormer_xy/world_size1-xytest/checkpoint_latest.pth ## for pretrained advective predictor

    # wandb:
    #   project_name: sevir